In [24]:
import numpy as np

**Array**

In [2]:
np.array(5)

array(5)

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [11]:
n = np.array([[1,2,3],[2,3,4]])
n

array([[1, 2, 3],
       [2, 3, 4]])

In [10]:
n[0]

array([1, 2, 3])

In [15]:
n[0][0]

1

In [16]:
n[0,0]

1

**Shape**

In [6]:
np.shape(np.array([1,2,3]))

(3,)

In [7]:
np.shape(np.array([[1,2,3],[2,3,4]]))

(2, 3)

**ndim**

In [17]:
np.ndim(np.array([1,2,3]))

1

In [18]:
np.ndim(np.array([[1,2,3],[2,3,4]]))

2

**Size**

In [25]:
np.size()

6

**dtype**

In [37]:
(np.array([[1,2,3],[2,3,4]])).dtype

dtype('int32')

In [42]:
arr = np.array([1,2,3,4,5,6,7], dtype="f")

In [43]:
arr.dtype

dtype('float32')

In [44]:
arr.shape

(7,)

In [45]:
arr.sort

<function ndarray.sort>

In [46]:
arr

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [62]:
np.trunc(np.array([1.5,2.6]))

array([1., 2.])

In [63]:
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]
